### ISSUE TITLE
Some errors on Windows

### ISSUE THREAD

**Issue by DekaSKy** [ZertyCraft/alienworlds-bot#1]
After start

Python 3.10.1 (tags/v3.10.1:2cd268a, Dec  6 2021, 19:10:37) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.

======== RESTART: C:\Users\Devos\Desktop\alienworlds-bot-master\mine.py ========
Error occurred during loading data. Trying to use cache server https://fake-useragent.herokuapp.com/browsers/0.1.11
Traceback (most recent call last):
  File "C:\Users\Devos\AppData\Local\Programs\Python\Python310\lib\site-packages\fake_useragent\utils.py", line 154, in load
    for item in get_browsers(verify_ssl=verify_ssl):
  File "C:\Users\Devos\AppData\Local\Programs\Python\Python310\lib\site-packages\fake_useragent\utils.py", line 99, in get_browsers
    html = html.split('<table class="w3-table-all notranslate">')[1]
IndexError: list index out of range
Traceback (most recent call last):
  File "C:\Users\Devos\AppData\Local\Programs\Python\Python310\lib\site-packages\fake_useragent\utils.py", line 154, in load
    for item in get_browsers(verify_ssl=verify_ssl):
  File "C:\Users\Devos\AppData\Local\Programs\Python\Python310\lib\site-packages\fake_useragent\utils.py", line 99, in get_browsers
    html = html.split('<table class="w3-table-all notranslate">')[1]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Devos\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "C:\Users\Devos\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\Devos\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\Devos\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\Devos\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1037, in _send_output
    self.send(msg)
  File "C:\Users\Devos\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 975, in send
    self.connect()
  File "C:\Users\Devos\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1454, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "C:\Users\Devos\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 512, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Users\Devos\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 1070, in _create
    self.do_handshake()
  File "C:\Users\Devos\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 1341, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Devos\AppData\Local\Programs\Python\Python310\lib\site-packages\fake_useragent\utils.py", line 64, in get
    with contextlib.closing(urlopen(
  File "C:\Users\Devos\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\Devos\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 519, in open
    response = self._open(req, data)
  File "C:\Users\Devos\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "C:\Users\Devos\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
  File "C:\Users\Devos\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "C:\Users\Devos\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Devos\Desktop\alienworlds-bot-master\mine.py", line 36, in <module>
    useragent = UserAgent()
  File "C:\Users\Devos\AppData\Local\Programs\Python\Python310\lib\site-packages\fake_useragent\fake.py", line 69, in __init__
    self.load()
  File "C:\Users\Devos\AppData\Local\Programs\Python\Python310\lib\site-packages\fake_useragent\fake.py", line 75, in load
    self.data = load_cached(
  File "C:\Users\Devos\AppData\Local\Programs\Python\Python310\lib\site-packages\fake_useragent\utils.py", line 250, in load_cached
    update(path, use_cache_server=use_cache_server, verify_ssl=verify_ssl)
  File "C:\Users\Devos\AppData\Local\Programs\Python\Python310\lib\site-packages\fake_useragent\utils.py", line 245, in update
    write(path, load(use_cache_server=use_cache_server, verify_ssl=verify_ssl))
  File "C:\Users\Devos\AppData\Local\Programs\Python\Python310\lib\site-packages\fake_useragent\utils.py", line 187, in load
    ret = json.loads(get(
  File "C:\Users\Devos\AppData\Local\Programs\Python\Python310\lib\site-packages\fake_useragent\utils.py", line 84, in get
    raise FakeUserAgentError('Maximum amount of retries reached')
fake_useragent.errors.FakeUserAgentError: Maximum amount of retries reached

**Comment by ZertyCraft** [comment]
Hello, thank you for your feedback.
I added the compatibility for Windows, as well as a step of the installation which is the installation of Python dependencies on Windows.

Normally the last version should work.
If not, don't hesitate to tell me.

**Comment by DekaSKy** [comment]
> Hello, thank you for your feedback. I added the compatibility for Windows, as well as a step of the installation which is the installation of Python dependencies on Windows.
> 
> Normally the last version should work. If not, don't hesitate to tell me.

Still the same error,how can I help?

**Comment by ZertyCraft** [comment]
Could you try opening the file mine.py in a text editor and deleting those three lines near the end of the file and trying again? (lines 220-222)

`useragent = UserAgent()`
`profile.set_preference("general.useragent.override", useragent.random)`
`profile.update_preferences()`

**Comment by DekaSKy** [comment]
> Could you try opening the file mine.py in a text editor and deleting those three lines near the end of the file and trying again? (lines 220-222)
> 
> `useragent = UserAgent()` `profile.set_preference("general.useragent.override", useragent.random)` `profile.update_preferences()`

Its work but not click on button Start Now
![image](https://user-images.githubusercontent.com/77372383/149540789-670848cb-8fa9-418c-a7d2-1edcc78f9437.png)

**Comment by DekaSKy** [comment]
I check xpath this button,replaced by /html/body/div/div[3]/div/div[1]/div/div and its work now for me

**Comment by ZertyCraft** [comment]
Thanks for your comments, I just updated the xpath.


I am currently working on the headless support.
I'm thinking of adding proxy options in a future update.

As for the multi-account, I don't know yet when I will add it.
